import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#f8f9fa' },
    centerContainer: { flexGrow: 1, justifyContent: 'center', padding: 20 },
    card: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 24,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
    },
    header: { fontSize: 20, fontWeight: 'bold', marginBottom: 24, color: '#212529' },
    formGroup: { marginBottom: 20 },
    label: { fontSize: 16, fontWeight: '500', color: '#495057', marginBottom: 8 },
    input: {
        borderWidth: 1,
        borderColor: '#ced4da',
        borderRadius: 6,
        padding: 12,
        fontSize: 16,
    },
    checkboxContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        padding: 16,
        backgroundColor: '#f1f3f5',
        borderRadius: 8,
    },
    checkboxWrapper: { flexDirection: 'row', alignItems: 'center' },
    checkLabel: { marginLeft: 8, fontSize: 14, color: '#495057' },
    footer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 10,
        paddingTop: 20,
        borderTopWidth: 1,
        borderTopColor: '#dee2e6',
    },
    backBtn: { paddingVertical: 10, paddingHorizontal: 20, marginRight: 10 },
    backBtnText: { color: '#6c757d', fontSize: 16 },
    addBtn: {
        backgroundColor: '#007bff',
        paddingVertical: 10,
        paddingHorizontal: 30,
        borderRadius: 6,
    },
    disabledBtn: { backgroundColor: '#a0c4ff' },
    addBtnText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
});